# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'airbnb' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for airbnb
 
 pod 'SwiftLint'
 pod 'SnapKit', '~> 5.6.0'

  target 'airbnbTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'airbnbUITests' do
    # Pods for testing
  end

end


