use_frameworks!

target 'airbnb' do
  pod 'SwiftLint'
  
  pod 'SnapKit', '~> 5.6.0'
  pod 'Alamofire'
  
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'RxAppState', '~> 1.6'
end

target 'airbnbTests' do
  #Quick은 테스트를 동작 주도 개발로 작성할 수 있도록 도와주는 프레임워크
  pod 'Quick'
  pod 'Nimble'
end